### ISSUE TITLE
undefined function ftp_connect()

### ISSUE THREAD

**Issue by owlyowl** [lafranceinsoumise/woocommerce-customer-order-csv-export#2]
Hi I'm getting this with an out of the box install on a fresh 

woocommerce
wordpress instance

Fatal error: Uncaught Error: Call to undefined function ftp_connect() in C:\wwwroot\wp-content\plugins\woocommerce-customer-order-csv-export\includes\export-methods\ftp\class-wc-customer-order-csv-export-method-ftp.php:66 Stack trace: #0 C:\wwwroot\wp-content\plugins\woocommerce-customer-order-csv-export\includes\class-wc-customer-order-csv-export-methods.php(146): WC_Customer_Order_CSV_Export_Method_FTP->__construct(Array) #1 C:\wwwroot\wp-content\plugins\woocommerce-customer-order-csv-export\includes\class-wc-customer-order-csv-export-handler.php(108): WC_Customer_Order_CSV_Export_Methods->get_export_method('ftp', 'orders') #2 C:\wwwroot\wp-content\plugins\woocommerce-customer-order-csv-export\includes\admin\class-wc-customer-order-csv-export-admin-settings.php(781): WC_Customer_Order_CSV_Export_Handler->test_export_via('ftp', 'orders') #3 C:\wwwroot\wp-content\plugins\woo in C:\wwwroot\wp-content\plugins\woocommerce-customer-order-csv-export\includes\export-methods\ftp\class-wc-customer-order-csv-export-method-ftp.php on line 66

**Comment by jillro** [comment]
Hello. This is not the original repository of this project and we are not its maintainers. Please get in touch with authors.
